"""Static lookups used by the UI (Latin binomial names, etc.).

Falls back gracefully — any class missing from the table simply renders
without its Latin name rather than erroring.
"""

LATIN_NAMES: dict[str, str] = {
    "MONARCH":              "Danaus plexippus",
    "VICEROY":              "Limenitis archippus",
    "QUEEN":                "Danaus gilippus",
    "PAINTED_LADY":         "Vanessa cardui",
    "RED_ADMIRAL":          "Vanessa atalanta",
    "MOURNING_CLOAK":       "Nymphalis antiopa",
    "COMMA":                "Polygonia c-album",
    "PEACOCK":              "Aglais io",
    "CABBAGE_WHITE":        "Pieris rapae",
    "CLOUDED_SULPHUR":      "Colias philodice",
    "TIGER_SWALLOWTAIL":    "Papilio glaucus",
    "BLACK_SWALLOWTAIL":    "Papilio polyxenes",
    "PIPEVINE_SWALLOWTAIL": "Battus philenor",
    "GIANT_SWALLOWTAIL":    "Papilio cresphontes",
    "ZEBRA_SWALLOWTAIL":    "Eurytides marcellus",
    "SPICEBUSH_SWALLOWTAIL":"Papilio troilus",
    "BLUE_MORPHO":          "Morpho peleides",
    "MORPHO":               "Morpho peleides",
    "BLUE_SPOTTED_CROW":    "Euploea midamus",
    "CRIMSON_PATCH":        "Chlosyne janais",
    "ATALA":                "Eumaeus atala",
    "ADONIS":               "Lysandra bellargus",
    "ADONIS_BLUE":          "Lysandra bellargus",
    "AMERICAN_SNOOT":       "Libytheana carinenta",
    "AN_88":                "Diaethria clymena",
    "BANDED_TIGER_MOTH":    "Apantesis nais",
    "BECKERS_WHITE":        "Pontia beckerii",
    "BLACK_HAIRSTREAK":     "Satyrium pruni",
    "BROWN_SIPROETA":       "Siproeta epaphus",
    "CAIRNS_BIRDWING":      "Ornithoptera euphorion",
    "CHECKERED_SKIPPER":    "Pyrgus communis",
    "CHESTNUT":             "Iolaus eurisus",
    "CLEOPATRA":            "Gonepteryx cleopatra",
    "CLODIUS_PARNASSIAN":   "Parnassius clodius",
    "COMMON_BANDED_AWL":    "Hasora chromus",
    "COMMON_WOOD_NYMPH":    "Cercyonis pegala",
    "COPPER_TAIL":          "Lycaena hyllus",
    "CRECENT":              "Phyciodes tharos",
    "CRESCENT":             "Phyciodes tharos",
    "DANAID_EGGFLY":        "Hypolimnas misippus",
    "EASTERN_COMA":         "Polygonia comma",
    "EASTERN_DAPPLED_WHITE":"Euchloe ausonides",
    "EASTERN_PINE_ELFIN":   "Callophrys niphon",
    "ELBOWED_PIERROT":      "Caleta elna",
    "GOLD_BANDED":          "Autochton cellus",
    "GREAT_EGGFLY":         "Hypolimnas bolina",
    "GREAT_JAY":            "Graphium eurypylus",
    "GREEN_CELLED_CATTLEHEART": "Parides childrenae",
    "GREY_HAIRSTREAK":      "Strymon melinus",
    "INDRA_SWALLOW":        "Papilio indra",
    "IPHICLUS_SISTER":      "Adelpha iphiclus",
    "JULIA":                "Dryas iulia",
    "LARGE_MARBLE":         "Euchloe ausonides",
    "MALACHITE":            "Siproeta stelenes",
    "MANGROVE_SKIPPER":     "Phocides pigmalion",
    "MESTRA":               "Mestra amymone",
    "METALMARK":            "Calephelis nemesis",
    "MILBERTS_TORTOISESHELL": "Aglais milberti",
    "ORANGE_OAKLEAF":       "Kallima inachus",
    "ORANGE_TIP":           "Anthocharis cardamines",
    "ORCHARD_SWALLOW":      "Papilio aegeus",
    "PAPER_KITE":           "Idea leuconoe",
    "PINE_WHITE":           "Neophasia menapia",
    "POPINJAY":             "Stibochiona nicea",
    "PURPLE_HAIRSTREAK":    "Favonius quercus",
    "PURPLISH_COPPER":      "Lycaena helloides",
    "QUESTION_MARK":        "Polygonia interrogationis",
    "RED_CRACKER":          "Hamadryas amphinome",
    "RED_POSTMAN":          "Heliconius erato",
    "RED_SPOTTED_PURPLE":   "Limenitis arthemis",
    "SCARCE_SWALLOW":       "Iphiclides podalirius",
    "SILVER_SPOT_SKIPPER":  "Epargyreus clarus",
    "SLEEPY_ORANGE":        "Abaeis nicippe",
    "SOOTYWING":            "Pholisora catullus",
    "SOUTHERN_DOGFACE":     "Zerene cesonia",
    "STRAITED_QUEEN":       "Danaus genutia",
    "TROPICAL_LEAFWING":    "Anaea aidea",
    "TWO_BARRED_FLASHER":   "Astraptes fulgerator",
    "ULYSES":               "Papilio ulysses",
    "WOOD_SATYR":           "Megisto cymela",
    "YELLOW_SWALLOW_TAIL":  "Papilio xuthus",
    "ZEBRA_LONG_WING":      "Heliconius charithonia",
}


def latin_for(name: str) -> str | None:
    """Return the Latin binomial for a class label, if known."""
    key = name.upper().replace(" ", "_").replace("-", "_")
    return LATIN_NAMES.get(key)
